# Generated by Django 5.1.2 on 2024-10-11 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mixiaozi", "0003_alter_cartitem_user_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/details/"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/details/"
                    ),
                ),
                ("price_text", models.CharField(max_length=255)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="mixiaozi.product",
                    ),
                ),
            ],
        ),
    ]
