# Generated by Django 5.1.2 on 2024-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mixiaozi", "0004_productdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=512)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
