# Generated by Django 5.1.2 on 2024-10-12 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mixiaozi", "0005_document_photo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="FaceImage",
        ),
    ]
